### PR TITLE
Fix missing icinga2.conf ITL includes

### PR DESCRIPTION
**Pull request by dnsmichi**
This mimics https://github.com/Icinga/icinga2/blob/master/etc/icinga2/win32/icinga2.conf

### CODE REVIEW

**Comment by LordHepipud** [comment]
Thanks - looks fine for me. Any other oppinions?

**Comment by dnsmichi** [comment]
I'd suggest to merge it, @lippserd knows about it. This affects ref/IP/22311

**Comment by lippserd** [comment]
Looks good 👍

**Comment by LordHepipud** [comment]
Thanks !

**Pull request merged**
